;
; File generated by cc65 v 2.19 - Git f5365c7
;
	.fopt		compiler,"cc65 v 2.19 - Git f5365c7"
	.setcpu		"65SC02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main
	.export		_stop

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	txa
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ stop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_stop: near

.segment	"CODE"

	rts

.endproc

